---
# CI Integration

image: python:3.6-stretch

stages:
  - build

before_script:
  - apt-get install -y -qqq zip
  - pip install pylint

  # Check code quality against sonarqube
sonar:
  stage: build
  variables:
    # CI vars
    CI_DEBUG_TRACE: "false"
    # Sonar vars
    SONAR_DEBUG: 1
    SONAR_VERSION: "3.2.0.1227-linux"
    SONAR_HOST: "http://sonarqube.ville.tg"
    SONAR_SCANNER_OPTS: "-Xmx512m"
  before_script:
    - test ${SONAR_DEBUG} -eq 1 && ls -la
    # Installs sonar-runner ZIP file
    - if [[ ! -d sonar-scanner-${SONAR_VERSION} ]]; then
    # yamllint disable-line rule:line-length
    - wget --no-verbose https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}.zip
    # yamllint disable-line rule:max-spaces-ahter
    - unzip -q sonar-scanner-cli-${SONAR_VERSION}.zip
    - fi

  script:
    - sonar-scanner-${SONAR_VERSION}/bin/sonar-scanner --version

    # Runs the sonar-runner
    - export SONAR_SCANNER_OPTS="-Xmx512m"
    - if [[ ${SONAR_DEBUG} -eq 1 ]]; then
    # yamllint disable-line rule:line-length
    - sonar-scanner-${SONAR_VERSION}/bin/sonar-scanner -X -Dsonar.host.url=$SONAR_HOST
    - else
    # yamllint disable-line rule:line-length
    - sonar-scanner-${SONAR_VERSION}/bin/sonar-scanner -Dsonar.host.url=$SONAR_HOST
    - fi
  cache:
    paths:
      - sonar-scanner-${SONAR_VERSION}/
      - .pip/
  tags:
    - python3.6
